const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  HIDE_CART: 'HIDE_CART',
  GET_ICON_NODE: 'GET_ICON_NODE',
  SET_FIREBASE_CART: 'SET_FIREBASE_CART'
};

export default CartActionTypes;
